### ISSUE TITLE
AttributeError: 'Settings' object has no attribute 'BULMA_SETTINGS'

### ISSUE THREAD

**Issue by oguzhanogreden** [python-discord/django-simple-bulma#12]
It seems the case where BULMA_SETTINGS is not defined is not handled well.

Perhaps consider:
- Updateing Readme.md to make it clear that this is needed even if it's empty,
- Catch the AttributeError and consider it empty.

Otherwise, the app enabled me to set up Bulma with great ease, thanks! 🎉

**Comment by heavysaturn** [comment]
mm, that's a good point. The latter would be far better, I'll have a go at that. Thanks for making an issue!

**Comment by heavysaturn** [comment]
@oguzhanogreden Solved in v1.1.1, which is live now at https://pypi.org/project/django-simple-bulma/.
