### ISSUE TITLE
AttributeError: module 'sass' has no attribute 'compile'

### ISSUE THREAD

**Issue by oguzhanogreden** [python-discord/django-simple-bulma#13]
Hi,

You attend to one issue so quickly, you get one more... :-)

If `sass` is installed next to `libsass`, this error is raised in `finders.py` line 57 (also [see](https://stackoverflow.com/questions/52327078/attributeerror-module-sass-has-no-attribute-compile)). This is clearly not your fault and a I can imagine a reliable solution in the app being cumbersome. 

Maybe a note in the Readme file would do it? This would help those of use who are not very well versed in web technologies.

Thanks,
Oguzhan

**Comment by heavysaturn** [comment]
I'll leave a note in the readme, and I'll also make collectstatic crash with an error explaining why this happens.

```UserWarning: There was an error compiling your Bulma CSS. This error is probably caused by having the `sass` module installed.
Please ensure you have only the `libsass` module installed, not both `sass` and `libsass`, or this application will not work.
```

**Comment by heavysaturn** [comment]
@oguzhanogreden Okay, solved in v1.1.2, which is live now on https://pypi.org/project/django-simple-bulma/.

I've added a note in the **Troubleshooting** section of the readme, and I've also made the error you're gonna get if you try to run `collectstatic` while `sass` is installed less cryptic and more informative.

**Comment by heavysaturn** [comment]
And again, thanks for reporting the bug to us. :+1:
