### ISSUE TITLE
Add PyPI release via GH Action

### ISSUE THREAD

**Issue by sco1** [python-discord/django-simple-bulma#32]
GH actions are approaching a point of maturity where they can be competently leaned on for automated deployment of releases to PyPI.

This project can likely utilize a similar approach [proposed by `flake8-annotations`](https://github.com/python-discord/flake8-annotations/issues/18), which uses the [`gh-action-pypi-publish`](https://github.com/pypa/gh-action-pypi-publish) action being developed under the PyPA namespace.

**Comment by lemonsaurus** [comment]
This has been added.
