### ISSUE TITLE
Upgrade to Django 3.*

### ISSUE THREAD

**Issue by bpepple** [python-discord/django-simple-bulma#37]
Looks like a least one change is needed to be make to django-simple-bulma work with for Django 3.*

* **django_simple_bulma.py** uses _'from django.contrib.staticfiles.templatetags.staticfiles import static'_ in it's imports and it looks like it was depreciated in Django-2.1* for _'django.templatetags.static.static()'_

* [https://docs.djangoproject.com/en/3.0/releases/2.1/#deprecated-features-2-1](https://docs.djangoproject.com/en/3.0/releases/2.1/#deprecated-features-2-1)

If I get a few free cycles I'll look at working up a fix, and see if there are any other changes that need to be made.

**Comment by MarkKoz** [comment]
This sounds like it's related to the open PR #36

**Comment by bpepple** [comment]
Didn't see the PR, but it looks like it's the same thing. Not quite sure why the PR is using '_from django.contrib.staticfiles.storage import staticfiles_storage'_ instead of what's in the release notes, but haven't looked into this other than at a cursory level, so maybe there's a good reason.

**Comment by talperetz** [comment]
Hey guys, I'm using django > 3
and I'd really like it if I could still use your awesome package
can you please merge my pull request [https://github.com/python-discord/django-simple-bulma/pull/38]
or solve this minor import issue?

**Comment by lemonsaurus** [comment]
Addressed in #38

**Comment by lemonsaurus** [comment]
@bpepple @talperetz 

We've released version 1.2.0 now on PyPI, which supports Django 3.x
