### ISSUE TITLE
New release: 1.2.0

### ISSUE THREAD

**Issue by lemonsaurus** [python-discord/django-simple-bulma#39]
For 1.2.0, we should add support for Django 2.2, Django 3.0 and Python 3.8.

- We've already merged #38, which should allow us to support Django 3.0.
- This app probably already supports Python 3.8, but this needs to be tested.

So here's what needs to be done before we release the 1.2.0:
- [x] Test `django-simple-bulma` inside a Django 3.0 app running Python 3.8, and verify that it still works as expected. 
- [ ] Make a pull request to the `setup.py` file and add Django 2.2, Django 3.0, Python 3.8 to the list of classifiers. 
- [ ] Also in the same pull request in `setup.py`, bump the version of `django-simple-bulma` to 1.2.0

Once this has been done, we can do a release to PyPI.

**Comment by talperetz** [comment]
I tested for django 3.0 and it works perfectly

**Comment by lemonsaurus** [comment]
that addresses half of the first checkbox. did you run it on py38, @talperetz?

**Comment by talperetz** [comment]
python 3.7 unfortunately

**Comment by lemonsaurus** [comment]
Tested OK on Py3.8 with Django 3.0.1
