### ISSUE TITLE
Alternative variables dict in BULMA_SETTINGS

### ISSUE THREAD

**Issue by lemonsaurus** [python-discord/django-simple-bulma#46]
In some cases, a website will want to have two themes, e.g. a dark theme and a light theme. To do this while using this plugin is tricky because all the scss variables are compiled at startup. But here's what we can do:

- If an `alt_variables` dict is present in `BULMA_SETTINGS`, we compile two css files, `bulma.css` and `bulma_alt.css`
- We create a template tag for adding this other css file as well, something like `{% bulma_alt %}`

Now the client can simply add this second dict of variables and define the dark theme that way, and then add some client logic to allow switching between them by switching which template tag is called in the templates.

**Comment by JonasUJ** [comment]
Why stop at one alternative? I'm thinking we let people add any number of `"{name}_variables"` in addition to the standard `"variables"`. The `{% bulma %}` tag could then be modified to accept an optional `name` argument, like this `{% bulma 'alt' %}`.

**Comment by lemonsaurus** [comment]
Interesting. I support this idea.

**Comment by lemonsaurus** [comment]
This is not in scope for v2.0.0, let's solve it for a future version.
