### ISSUE TITLE
Update Bulma to latest version

### ISSUE THREAD

**Issue by JonasUJ** [python-discord/django-simple-bulma#47]
The version used by this project is now almost 2 years old and a lot of features have been released since.

**Comment by lemonsaurus** [comment]
Hi @JonasUJ, thanks for opening this issue!

This project hasn't been very actively maintained, however, this organisation is a hotbed of activity and we haven't forgotten about this repo. We'd be happy to accept a pull request that updates the version, if you're willing to open one.

**Comment by lemonsaurus** [comment]
Closed by #48
