### ISSUE TITLE
Allow this app to load additional sass files

### ISSUE THREAD

**Issue by heavysaturn** [python-discord/django-simple-bulma#5]
Some users may want to customize their site beyond what can be done by changing bulma variables. For this, we could offer the option of loading additional sass files. I'm not sure how best to do this, so I'm inviting anyone reading this to discuss it in this issue. Here are a couple of potential ways:

- Take a new BULMA_SETTINGS configuration parameter called `additional_sass`, which is a list of `PosixPath`s pointing at additional sass files that `django-simple-bulma` should load along with bulma. This means it would add that css onto the already huge css file that bulma + extensions makes, so it's not a very optimized solution, but since most users probably won't be adding more than a couple of lines of their own sass anyway, that might be okay.

- Tell the user to put their `.sass` files in a specific location (`$root/static/sass/` or something) and then compile all the files in this folder to css files of the same name whenever `collectstatic` is run. Then the user would manually load these by just using `{% static "css/mycoolfile.css" %}`. Saves the user the hassle of dealing with libsass directly, but isn't as smooth as just loading it with that `{% bulma %}` tag.

- Tell the user to put all their desired additional sass into a specific file in a specific location, like `$project_root/static/bulma_additional.sass`. Then just import that file at the end of the `bulma.sass`. This is pretty easy and less error prone, but might be messy if the user needs a lot of sass. Again, though, I think that's probably rare.

**Comment by gdude2002** [comment]
This feels a little too feature-creepy to me. I kinda feel like this belongs in another package? But there's already plenty that do this already, right?

**Comment by heavysaturn** [comment]
https://github.com/jrief/django-sass-processor/ actually this looks great. I guess you're right regarding feature creep.
