### ISSUE TITLE
Missing files in v2.0.0 release files

### ISSUE THREAD

**Issue by bpepple** [python-discord/django-simple-bulma#61]
Updating to v2.0.0, and it looks like the submodules you're using now aren't included in the tarball. Since I get the following error when attempting to run django.

`FileNotFoundError: [Errno 2] No such file or directory: '/home/bpepple/.local/share/virtualenvs/metron-UZX73b7p/lib/python3.6/site-packages/django_simple_bulma/bulma/sass'`

Pulled the tarball down from the release page, and verified the bulma folder is empty.

**Comment by bpepple** [comment]
Glancing at your setup.py and I see you're using 'package_data', which if I remember correctly works only with bdist and not sdist. I believe you need to add a 'MANIFEST.in' for sdist, and the 'package_data' will be used for bdist.

If you don't get to it before tonight, I can probably work-up a quick pull request.

**Comment by lemonsaurus** [comment]
Looks like you're right, sorry for any inconvenience caused. 

I don't have time to look into this today but I'll try to get it sorted out ASAP. If you or anyone else reading this has any ideas or would like to open a PR with a fix, that'd be much appreciated.

**Comment by lemonsaurus** [comment]
@bpepple I believe this should be resolved now.

The problem was that we were not checking out the submodules in the GitHub Actions workflow that was responsible for building the source distribution.

Could you verify that everything works as expected in release 2.0.2, when you get a chance?

**Comment by bpepple** [comment]
> Could you verify that everything works as expected in release 2.0.2, when you get a chance?

Did a quick update, and that looks like it fixed it. If there are any another problems in regard to this release I'll open another bug.

**Comment by lemonsaurus** [comment]
Thanks @bpepple, we really appreciate you taking the time to report these bugs to us!
