### ISSUE TITLE
Versioning

### ISSUE THREAD

**Issue by gdude2002** [python-discord/django-simple-bulma#8]
While I think it's a good idea to ship Bulma's assets (and that of its extensions) with the PyPi release, it would be nice to be able to specify the specific versions wanted of those for users that do have the option to download those dependencies in their environment.

We'd need to cache them somewhere, of course.

**Comment by heavysaturn** [comment]
not sure I see much value in this. why would anyone ever want an older version?

**Comment by gdude2002** [comment]
Compatibility was my main thought. Bulma updates but extensions don't, situations like that.

**Comment by heavysaturn** [comment]
theoretically we could do this by letting the user specify versions for everything in `BULMA_SETTINGS`, and if these were specified, getting rid of the .sass and .js files that ship with `django-simple-bulma` and somehow downloading the right version. No real need to cache a whole bunch of versions as this is likely to only happen once, and a single slow `collectstatic` seems like an acceptable trade-off. 

That said, this would represent a big rewrite, so I'm gonna leave this issue open and if anyone really needs this feature they can leave a note here. I don't know if I see there being much of a demand for it, but if I'm wrong I'm happy to implement it.

**Comment by lemonsaurus** [comment]
I don't think we need this.
